spring:
  application:
    name: portfolio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

schema:
  database-name: ${DATABASE_NAME}