environment:
  name: DEV
server:
  port : 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:4444/portfolio?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: Amadeus1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

files:
  base-dir: C:/ProgramData/temp/