version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "${DATABASE_PORT}:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    db:
      driver: local